### ISSUE TITLE
cant run it under router 

### ISSUE THREAD

**Issue by swetoast** [dante-signal31/geolocate#1]
/opt/home/admin # pip install glocate
Collecting glocate
  Downloading glocate-1.2.1.tar.gz
Collecting geoip2>=2.1.0 (from glocate)
  Using cached geoip2-2.1.0-py2.py3-none-any.whl
Collecting maxminddb>=1.1.1 (from glocate)
  Using cached maxminddb-1.2.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests>=2.5.0 in /opt/lib/python2.7/site-packages (from glocate)
Collecting wget>=2.2 (from glocate)
  Downloading wget-2.2.tar.gz
Collecting ipaddr (from maxminddb>=1.1.1->glocate)
  Using cached ipaddr-2.1.11.tar.gz
Installing collected packages: ipaddr, maxminddb, geoip2, wget, glocate
  Running setup.py install for ipaddr
  Running setup.py install for maxminddb
  Running setup.py install for wget
  Running setup.py install for glocate
Successfully installed geoip2-2.1.0 glocate-1.2.1 ipaddr-2.1.11 maxminddb-1.2.0 wget-2.2

/opt/home/admin # geolocate --help
Traceback (most recent call last):
  File "/opt/bin/geolocate", line 9, in <module>
    load_entry_point('glocate==1.2.1', 'console_scripts', 'geolocate')()
  File "/opt/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/pkg_resources/**init**.py", line 552, in load_entry_point
  File "/opt/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/pkg_resources/**init**.py", line 2672, in load_entry_point
  File "/opt/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/pkg_resources/**init**.py", line 2345, in load
  File "/opt/lib/python2.7/site-packages/setuptools-16.0-py2.7.egg/pkg_resources/**init**.py", line 2351, in resolve
  File "/opt/lib/python2.7/site-packages/geolocate/glocate.py", line 26
    print(line, end="")
                   ^

**Comment by dante-signal31** [comment]
Hello @swetoast, as you can read on [geolocate installation wiki page](https://github.com/dante-signal31/geolocate/wiki/Installation):

_Geolocate is programmed with Python 3.4, running it with any previous version may not work completely or anything at all._

Besides, in [Geolocate PyPi page](https://pypi.python.org/pypi/glocate/) this application is officially categorized as a Python 3.x one.

It seems you're trying to run it using Python 2.7, that has many API incompatibilities with latest Python's versions (like 3.4 one). The first incompatibility is that Python 2.7's print statement has evolved in Python 3.4 to a function, so it is called in a radically different way. It's normal that program crashed in that point when executed on Python 2.7 instead that on Python 3.4.

Try to install, latest Python stable version (3.4). Don't worry about your current Python installation, Python 3.x and Python 2.7 can live in the same system. Afterwards install geolocate using **pip3** command. Pip comes by default with Python since 3.4 version but its executable is called pip3 to avoid naming collisions with pip versions you could have installed with Python 2.7. Doing this, geolocate should run fine.

Please, tell me if this solves your problem.

**Comment by dante-signal31** [comment]
_"No news good news"_.

I assume diagnostic was right and I'm going to close this issue.

Besides, I've updated Geolocate to check Python interpreter version it is being executed under. From now on, if it detects it is being run under Python 2.x it will warn user that she is using an unsupported Python version and will abort execution gracefully.
